// World: Trees — DFS & BFS

export const TREES_TRICKS = [
  {
    id: 'trees/recursive-dfs',
    name: 'Recursive DFS template',
    when: 'Compute a property of a tree from its subtrees — height, sums, validity',
    code: [
      'def dfs(node):',
      '    if {{not node}}:',
      '        return 0                    # base case',
      '    left = dfs({{node.left}})',
      '    right = dfs(node.right)',
      '    return {{1 + max(left, right)}}  # combine (height here)',
    ],
    bigO: { time: 'O(n)', space: 'O(h) recursion stack' },
    gotchas: [
      'The None-check IS the base case — trust the recursion for the rest',
      'Stack space is O(h): O(log n) balanced, O(n) for a skewed tree',
      'Answers flow BOTTOM-UP through the return values',
    ],
    quiz: [
      {
        q: 'DFS recursion space on a completely skewed tree?',
        options: ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'],
        answer: 2,
        why: 'The call stack is as deep as the tree — n frames when it is a chain.',
      },
    ],
    problems: [
      { title: 'Maximum Depth of Binary Tree', diff: 'E', slug: 'maximum-depth-of-binary-tree' },
      { title: 'Diameter of Binary Tree', diff: 'E', slug: 'diameter-of-binary-tree' },
      { title: 'Balanced Binary Tree', diff: 'E', slug: 'balanced-binary-tree' },
      { title: 'Invert Binary Tree', diff: 'E', slug: 'invert-binary-tree' },
    ],
  },
  {
    id: 'trees/iterative-dfs',
    name: 'Iterative DFS (explicit stack)',
    when: 'Traverse without recursion — no stack-overflow risk, and you can pause anytime',
    code: [
      'stack = [{{root}}]',
      'while stack:',
      '    node = stack{{.pop()}}',
      '    if not node:',
      '        continue',
      '    visit(node)                    # preorder position',
      '    stack.append({{node.right}})    # right first…',
      '    stack.append(node.left)        # …so left pops first',
    ],
    bigO: { time: 'O(n)', space: 'O(h) to O(n)' },
    gotchas: [
      'Push RIGHT before LEFT — the stack reverses the order',
      'Inorder needs the "walk down the left spine" variant',
      'A stack of (node, visited_flag) pairs emulates any traversal order',
    ],
    quiz: [
      {
        q: 'To visit left before right with a stack, you push…',
        options: ['left first', 'right first', 'both at once', 'neither — use a queue'],
        answer: 1,
        why: 'LIFO: the last push pops first.',
      },
    ],
    problems: [
      { title: 'Binary Tree Preorder Traversal', diff: 'E', slug: 'binary-tree-preorder-traversal' },
      { title: 'Binary Tree Inorder Traversal', diff: 'E', slug: 'binary-tree-inorder-traversal' },
      { title: 'Kth Smallest Element in a BST', diff: 'M', slug: 'kth-smallest-element-in-a-bst' },
      { title: 'Flatten Binary Tree to Linked List', diff: 'M', slug: 'flatten-binary-tree-to-linked-list' },
    ],
  },
  {
    id: 'trees/bfs-levels',
    name: 'BFS level-order (level-size snapshot)',
    when: 'Process a tree level by level — depths, per-level stats, rightmost views',
    code: [
      'q = deque([root])',
      'while q:',
      '    level = []',
      '    for _ in range({{len(q)}}):     # freeze THIS level’s size',
      '        node = q{{.popleft()}}',
      '        level.append(node.val)',
      '        if node.left:',
      '            q.append(node.left)',
      '        if node.right:',
      '            q.append({{node.right}})',
      '    out.append(level)',
    ],
    bigO: { time: 'O(n)', space: 'O(max width)' },
    gotchas: [
      'The len(q) snapshot is what separates levels — the whole trick',
      'Check children before enqueueing and you never handle None',
      'Right-side view = the last element of each level',
    ],
    quiz: [
      {
        q: 'Why snapshot len(q) before the inner loop?',
        options: [
          'Performance',
          'The queue grows during the loop — the snapshot bounds exactly one level',
          'deque requires it',
          'To avoid popleft errors',
        ],
        answer: 1,
        why: 'Children enqueued mid-loop belong to the NEXT level; the frozen count stops before them.',
      },
    ],
    problems: [
      { title: 'Binary Tree Level Order Traversal', diff: 'M', slug: 'binary-tree-level-order-traversal' },
      { title: 'Binary Tree Right Side View', diff: 'M', slug: 'binary-tree-right-side-view' },
      { title: 'Binary Tree Zigzag Level Order Traversal', diff: 'M', slug: 'binary-tree-zigzag-level-order-traversal' },
      { title: 'Minimum Depth of Binary Tree', diff: 'E', slug: 'minimum-depth-of-binary-tree' },
    ],
  },
  {
    id: 'trees/grid-dfs',
    name: 'Grid DFS (flood fill)',
    when: 'Explore a connected region of a 2-D grid — islands, fills, enclosed areas',
    code: [
      'def dfs(r, c):',
      '    if (r < 0 or r >= rows or c < 0 or c >= cols',
      '            or grid[r][c] != "1"):',
      '        return',
      '    grid[r][c] = {{"0"}}            # mark visited IN PLACE',
      '    for dr, dc in {{[(1,0), (-1,0), (0,1), (0,-1)]}}:',
      '        dfs(r + dr, c + dc)',
    ],
    bigO: { time: 'O(rows·cols)', space: 'O(rows·cols) worst-case stack' },
    gotchas: [
      'Mark visited BEFORE recursing or you recurse forever',
      'Mutating the grid replaces a visited set — ask the interviewer if that is allowed',
      'One combined bounds-plus-value guard keeps the code clean',
    ],
    quiz: [
      {
        q: 'Forgetting to mark cells visited causes…',
        options: ['Wrong counts only', 'Infinite recursion between neighbors', 'An IndexError', 'Nothing — it still works'],
        answer: 1,
        why: 'Two adjacent land cells call each other forever.',
      },
    ],
    problems: [
      { title: 'Number of Islands', diff: 'M', slug: 'number-of-islands' },
      { title: 'Max Area of Island', diff: 'M', slug: 'max-area-of-island' },
      { title: 'Surrounded Regions', diff: 'M', slug: 'surrounded-regions' },
      { title: 'Pacific Atlantic Water Flow', diff: 'M', slug: 'pacific-atlantic-water-flow' },
    ],
  },
  {
    id: 'trees/bst-bounds',
    name: 'BST bounds validation',
    when: 'Verify or exploit the ordering invariant — every node is bounded by ALL its ancestors',
    code: [
      'def valid(node, lo, hi):',
      '    if not node:',
      '        return True',
      '    if not ({{lo < node.val < hi}}):',
      '        return False',
      '    return (valid(node.left, lo, {{node.val}}) and',
      '            valid(node.right, node.val, hi))',
      '',
      'valid(root, float("-inf"), float("inf"))',
    ],
    bigO: { time: 'O(n)', space: 'O(h)' },
    gotchas: [
      'Comparing only parent vs child misses violations deeper down — pass BOUNDS',
      'Alternative check: an inorder traversal of a BST must come out sorted',
      'Start with ±infinity sentinels',
    ],
    quiz: [
      {
        q: 'Why is checking each node only against its children insufficient?',
        options: [
          'It is sufficient',
          'A grandchild can violate a grandparent’s bound while satisfying its parent',
          'Children may be None',
          'It is too slow',
        ],
        answer: 1,
        why: 'E.g. root 10, left 5, left.right 12 — locally fine, globally broken.',
      },
    ],
    problems: [
      { title: 'Validate Binary Search Tree', diff: 'M', slug: 'validate-binary-search-tree' },
      { title: 'Kth Smallest Element in a BST', diff: 'M', slug: 'kth-smallest-element-in-a-bst' },
      { title: 'Lowest Common Ancestor of a BST', diff: 'M', slug: 'lowest-common-ancestor-of-a-binary-search-tree' },
      { title: 'Insert into a Binary Search Tree', diff: 'M', slug: 'insert-into-a-binary-search-tree' },
    ],
  },
];
