// World: Graphs

export const GRAPHS_TRICKS = [
  {
    id: 'graphs/adjacency',
    name: 'Edge list → adjacency list',
    when: 'The first line of nearly every graph problem — turn edge pairs into neighbor lookups',
    code: [
      'from collections import defaultdict',
      'graph = defaultdict(list)',
      'for u, v in edges:',
      '    graph[u].append({{v}})',
      '    graph[v].append({{u}})    # undirected: BOTH directions',
    ],
    bigO: { time: 'O(V + E)', space: 'O(V + E)' },
    gotchas: [
      'Directed graphs get only u→v — adding both silently breaks toposort',
      'Isolated nodes never appear in the dict — iterate range(n), not graph.keys()',
    ],
    quiz: [
      {
        q: 'For a DIRECTED edge u→v you add…',
        options: ['both directions', 'only graph[u].append(v)', 'only graph[v].append(u)', 'a weight of 1'],
        answer: 1,
        why: 'Direction is information — mirroring it invents edges that do not exist.',
      },
    ],
    problems: [
      { title: 'Number of Connected Components in an Undirected Graph', diff: 'M', slug: 'number-of-connected-components-in-an-undirected-graph' },
      { title: 'Course Schedule', diff: 'M', slug: 'course-schedule' },
      { title: 'Clone Graph', diff: 'M', slug: 'clone-graph' },
    ],
  },
  {
    id: 'graphs/bfs-shortest',
    name: 'BFS shortest path (unweighted)',
    when: 'Fewest steps from A to B when every step costs the same',
    code: [
      'q = deque([(start, 0)])',
      'seen = {start}',
      'while q:',
      '    node, dist = q.popleft()',
      '    if node == goal:',
      '        return dist',
      '    for nxt in graph[node]:',
      '        if nxt {{not in seen}}:',
      '            seen.add({{nxt}})            # mark when ENQUEUED',
      '            q.append((nxt, {{dist + 1}}))',
    ],
    bigO: { time: 'O(V + E)', space: 'O(V)' },
    gotchas: [
      'Mark seen at ENQUEUE time — marking at dequeue lets duplicates flood the queue',
      'BFS finds shortest paths only when edges are UNWEIGHTED (else Dijkstra)',
      'Multi-source BFS: seed the queue with every source at distance 0',
    ],
    quiz: [
      {
        q: 'Marking nodes seen at dequeue (not enqueue) causes…',
        options: [
          'Wrong answers',
          'The same node queued many times — blow-up, though answers stay correct',
          'A crash',
          'Nothing different',
        ],
        answer: 1,
        why: 'Correct but potentially exponential queue growth — the classic BFS perf bug.',
      },
    ],
    problems: [
      { title: 'Rotting Oranges', diff: 'M', slug: 'rotting-oranges' },
      { title: 'Shortest Path in Binary Matrix', diff: 'M', slug: 'shortest-path-in-binary-matrix' },
      { title: 'Open the Lock', diff: 'M', slug: 'open-the-lock' },
      { title: 'Word Ladder', diff: 'H', slug: 'word-ladder' },
    ],
  },
  {
    id: 'graphs/union-find',
    name: 'Union-Find (path compression + rank)',
    when: 'Dynamic connectivity — merge groups and answer "same group?" in near-constant time',
    code: [
      'parent = list(range(n))',
      'rank = [0] * n',
      'def find(x):',
      '    while parent[x] != x:',
      '        parent[x] = {{parent[parent[x]]}}   # path halving',
      '        x = parent[x]',
      '    return x',
      'def union(a, b):',
      '    ra, rb = find(a), find(b)',
      '    if ra == rb:',
      '        return False               # already connected → cycle!',
      '    if rank[ra] < rank[rb]:',
      '        ra, rb = rb, ra',
      '    parent[rb] = {{ra}}',
      '    if rank[ra] == rank[rb]:',
      '        rank[ra] += 1',
      '    return True',
    ],
    bigO: { time: 'O(α(n)) ≈ O(1) amortized per op', space: 'O(n)' },
    gotchas: [
      'union returning False = the edge closes a cycle — free cycle detection',
      'Skip compression and chains degrade find to O(n)',
      'Component count: start at n, subtract 1 per successful union',
    ],
    quiz: [
      {
        q: 'α(n) in the union-find bound is…',
        options: [
          'The golden ratio',
          'Inverse Ackermann — ≤ 5 for any realistic n',
          'log log n',
          'Amortized constant by definition',
        ],
        answer: 1,
        why: 'It grows so slowly it is effectively constant — say this in interviews.',
      },
    ],
    problems: [
      { title: 'Redundant Connection', diff: 'M', slug: 'redundant-connection' },
      { title: 'Number of Connected Components in an Undirected Graph', diff: 'M', slug: 'number-of-connected-components-in-an-undirected-graph' },
      { title: 'Graph Valid Tree', diff: 'M', slug: 'graph-valid-tree' },
      { title: 'Accounts Merge', diff: 'M', slug: 'accounts-merge' },
    ],
  },
  {
    id: 'graphs/topo-sort',
    name: "Topological sort (Kahn's BFS)",
    when: 'Order tasks under prerequisites — and detect when no valid order exists',
    code: [
      'indeg = [0] * n',
      'for u, v in edges:          # u must come before v',
      '    graph[u].append(v)',
      '    indeg[v] += 1',
      'q = deque([i for i in range(n) if {{indeg[i] == 0}}])',
      'order = []',
      'while q:',
      '    u = q.popleft()',
      '    order.append(u)',
      '    for v in graph[u]:',
      '        indeg[v] -= 1',
      '        if {{indeg[v] == 0}}:',
      '            q.append(v)',
      '# len(order) < n  →  cycle',
    ],
    bigO: { time: 'O(V + E)', space: 'O(V + E)' },
    gotchas: [
      'len(order) < n means a cycle — some nodes never reached indegree 0',
      'Seed the queue with ALL zero-indegree nodes, not just one',
      'DFS-with-colors is the recursive alternative for cycle detection',
    ],
    quiz: [
      {
        q: "How does Kahn's algorithm report a cycle?",
        options: [
          'It raises an exception',
          'The output order is shorter than n',
          'indegrees go negative',
          'The queue never empties',
        ],
        answer: 1,
        why: 'Nodes inside a cycle never hit indegree 0, so they never enter the order.',
      },
    ],
    problems: [
      { title: 'Course Schedule', diff: 'M', slug: 'course-schedule' },
      { title: 'Course Schedule II', diff: 'M', slug: 'course-schedule-ii' },
      { title: 'Minimum Height Trees', diff: 'M', slug: 'minimum-height-trees' },
      { title: 'Alien Dictionary', diff: 'H', slug: 'alien-dictionary' },
    ],
  },
  {
    id: 'graphs/dijkstra',
    name: 'Dijkstra with a heap',
    when: 'Shortest paths when edges have different (non-negative) costs',
    code: [
      'dist = {start: 0}',
      'heap = [(0, start)]',
      'while heap:',
      '    d, u = heapq.heappop(heap)',
      '    if d > dist.get(u, {{float("inf")}}):',
      '        continue                  # stale entry — skip',
      '    for v, w in graph[u]:',
      '        nd = {{d + w}}',
      '        if nd < dist.get(v, float("inf")):',
      '            dist[v] = nd',
      '            heapq.heappush(heap, {{(nd, v)}})',
    ],
    bigO: { time: 'O(E log V)', space: 'O(V + E)' },
    gotchas: [
      'Lazy deletion: pop, then SKIP entries worse than the best known distance',
      'Negative edges break the greedy argument — Bellman-Ford instead',
      'The tuple is (distance, node) — priority first, always',
    ],
    quiz: [
      {
        q: 'Dijkstra fails when the graph has…',
        options: ['Cycles', 'Negative-weight edges', 'Disconnected parts', 'More edges than nodes'],
        answer: 1,
        why: 'A negative edge can improve an already-finalized node — the greedy invariant dies.',
      },
    ],
    problems: [
      { title: 'Network Delay Time', diff: 'M', slug: 'network-delay-time' },
      { title: 'Path With Minimum Effort', diff: 'M', slug: 'path-with-minimum-effort' },
      { title: 'Cheapest Flights Within K Stops', diff: 'M', slug: 'cheapest-flights-within-k-stops' },
      { title: 'Swim in Rising Water', diff: 'H', slug: 'swim-in-rising-water' },
    ],
  },
];
