// World: Matrix & Simulation

export const MATRIX_TRICKS = [
  {
    id: 'matrix/spiral',
    name: 'Spiral traversal (shrinking bounds)',
    when: 'Walk a grid in a spiral — maintain four walls and close them in',
    code: [
      'top, bottom = 0, rows - 1',
      'left, right = 0, cols - 1',
      'while top <= bottom and left <= right:',
      '    for c in range(left, right + 1):',
      '        out.append(grid[top][c])',
      '    {{top += 1}}',
      '    for r in range(top, bottom + 1):',
      '        out.append(grid[r][right])',
      '    right -= 1',
      '    if {{top <= bottom}}:              # guard: row may be gone',
      '        for c in range(right, left - 1, -1):',
      '            out.append(grid[bottom][c])',
      '        bottom -= 1',
      '    if left <= right:',
      '        for r in range(bottom, top - 1, -1):',
      '            out.append(grid[r][left])',
      '        {{left += 1}}',
    ],
    bigO: { time: 'O(rows·cols)', space: 'O(1) extra' },
    gotchas: [
      'The two guards prevent double-walking a single leftover row/column',
      'Shrink each wall immediately after consuming it',
    ],
    quiz: [
      {
        q: 'Skipping the `if top <= bottom` guard breaks on…',
        options: ['Square matrices', 'Single-row leftovers (duplicates them)', 'Empty matrices only', 'Nothing'],
        answer: 1,
        why: 'After the top pass consumed the last row, the bottom pass would re-walk it backwards.',
      },
    ],
    problems: [
      { title: 'Spiral Matrix', diff: 'M', slug: 'spiral-matrix' },
      { title: 'Spiral Matrix II', diff: 'M', slug: 'spiral-matrix-ii' },
      { title: 'Rotate Image', diff: 'M', slug: 'rotate-image' },
    ],
  },
  {
    id: 'matrix/rotate',
    name: 'Rotate 90° = transpose + reverse',
    when: 'Rotate a square matrix in place — two simple reflections compose into a rotation',
    code: [
      'n = len(grid)',
      'for i in range(n):                  # transpose (flip over diagonal)',
      '    for j in range({{i + 1}}, n):     # j > i: touch each pair once',
      '        grid[i][j], grid[j][i] = grid[j][i], grid[i][j]',
      'for row in grid:                    # then mirror horizontally',
      '    row{{.reverse()}}',
    ],
    bigO: { time: 'O(n²)', space: 'O(1)' },
    gotchas: [
      'range(i+1, n) — starting at 0 would swap every pair TWICE (a no-op)',
      'Counter-clockwise: transpose then reverse COLUMNS (or reverse rows first)',
    ],
    quiz: [
      {
        q: 'Transposing with j starting at 0 instead of i+1 yields…',
        options: ['A 180° rotation', 'The original matrix (double swap)', 'A crash', 'The correct transpose'],
        answer: 1,
        why: 'Each (i,j)/(j,i) pair gets swapped twice — back to where it started.',
      },
    ],
    problems: [
      { title: 'Rotate Image', diff: 'M', slug: 'rotate-image' },
      { title: 'Transpose Matrix', diff: 'E', slug: 'transpose-matrix' },
      { title: 'Determine Whether Matrix Can Be Obtained By Rotation', diff: 'E', slug: 'determine-whether-matrix-can-be-obtained-by-rotation' },
    ],
  },
  {
    id: 'matrix/coord-keys',
    name: 'Coordinate keys: i+j, i−j, (i//3, j//3)',
    when: 'Group cells by diagonal, anti-diagonal, or sub-box with one arithmetic key',
    code: [
      'diag = defaultdict(list)',
      'for i in range(rows):',
      '    for j in range(cols):',
      '        diag[{{i - j}}].append(grid[i][j])    # ↘ diagonals share i-j',
      '        anti[{{i + j}}].append(grid[i][j])    # ↗ anti-diagonals share i+j',
      '        box[{{(i // 3, j // 3)}}].add(grid[i][j])   # sudoku boxes',
    ],
    bigO: { time: 'O(rows·cols)', space: 'O(rows·cols)' },
    gotchas: [
      'i−j is constant along ↘ diagonals; i+j along ↗ anti-diagonals',
      'Integer-divide both coordinates to bucket into fixed-size boxes',
      'The same keys power N-queens attack detection',
    ],
    quiz: [
      {
        q: 'Cells (2,0) and (3,1) share which key?',
        options: ['i + j', 'i − j', 'i * j', '(i//3, j//3)'],
        answer: 1,
        why: '2−0 = 3−1 = 2 — same ↘ diagonal.',
      },
    ],
    problems: [
      { title: 'Valid Sudoku', diff: 'M', slug: 'valid-sudoku' },
      { title: 'Diagonal Traverse', diff: 'M', slug: 'diagonal-traverse' },
      { title: 'N-Queens', diff: 'H', slug: 'n-queens' },
      { title: 'Sort the Matrix Diagonally', diff: 'M', slug: 'sort-the-matrix-diagonally' },
    ],
  },
  {
    id: 'matrix/inplace-flags',
    name: 'First row/col as in-place flags',
    when: 'Mark whole rows/columns for update without an O(m+n) bookkeeping array',
    code: [
      'for i in range(rows):',
      '    for j in range(cols):',
      '        if grid[i][j] == 0:',
      '            grid[i][{{0}}] = 0        # flag the row in column 0',
      '            grid[{{0}}][j] = 0        # flag the col in row 0',
      '# second pass: apply flags (iterate from 1, handle row/col 0 last)',
      'for i in range(1, rows):',
      '    for j in range(1, cols):',
      '        if grid[i][0] == 0 or grid[0][j] == 0:',
      '            grid[i][j] = {{0}}',
    ],
    bigO: { time: 'O(rows·cols)', space: 'O(1)' },
    gotchas: [
      'Row 0 / col 0 double as storage — remember their OWN state in two booleans first',
      'Apply flags starting from (1,1) so you don’t destroy the flags mid-pass',
    ],
    quiz: [
      {
        q: 'Why process row 0 and column 0 last?',
        options: [
          'They are usually empty',
          'They store the flags — clearing them early corrupts the bookkeeping',
          'Cache locality',
          'They cannot contain zeros',
        ],
        answer: 1,
        why: 'The border is your notebook; erase it only after reading everything.',
      },
    ],
    problems: [
      { title: 'Set Matrix Zeroes', diff: 'M', slug: 'set-matrix-zeroes' },
      { title: 'Game of Life', diff: 'M', slug: 'game-of-life' },
      { title: 'Rotate Image', diff: 'M', slug: 'rotate-image' },
    ],
  },
  {
    id: 'matrix/state-encode',
    name: 'In-place state encoding',
    when: 'Update every cell "simultaneously" — encode old AND new state in one value',
    code: [
      '# game of life: bit 0 = current, bit 1 = next generation',
      'for i in range(rows):',
      '    for j in range(cols):',
      '        live = count_live_neighbors(i, j)   # reads bit 0 only: {{cell & 1}}',
      '        if grid[i][j] & 1 and live in (2, 3):',
      '            grid[i][j] |= {{2}}               # survives → set bit 1',
      '        elif not (grid[i][j] & 1) and live == 3:',
      '            grid[i][j] |= 2                  # born',
      'for i in range(rows):',
      '    for j in range(cols):',
      '        grid[i][j] {{>>= 1}}                  # commit: next becomes current',
    ],
    bigO: { time: 'O(rows·cols)', space: 'O(1)' },
    gotchas: [
      'Neighbors must read the OLD state — masking with &1 is what makes in-place safe',
      'Any two-symbol encoding works: e.g. mark dying cells as -1, born as 2, decode after',
    ],
    quiz: [
      {
        q: 'Why can’t you just write the new value directly during the pass?',
        options: [
          'Python forbids it',
          'Later cells would read already-updated neighbors — the generations blur',
          'It is slower',
          'You can — it is fine',
        ],
        answer: 1,
        why: 'Simultaneous update means every read must see generation N while writing N+1.',
      },
    ],
    problems: [
      { title: 'Game of Life', diff: 'M', slug: 'game-of-life' },
      { title: 'Set Matrix Zeroes', diff: 'M', slug: 'set-matrix-zeroes' },
      { title: 'Rotting Oranges', diff: 'M', slug: 'rotting-oranges' },
    ],
  },
];
