// World: Graphs

export const GRAPHS_TRICKS = [
  {
    id: 'graphs/adjacency',
    name: 'Edge list → adjacency list',
    when: 'The first line of nearly every graph problem — turn edge pairs into neighbor lookups',
    code: [
      'from collections import defaultdict',
      'graph = defaultdict(list)',
      'for u, v in edges:',
      '    graph[u].append({{v}})',
      '    graph[v].append({{u}})    # undirected: BOTH directions',
    ],
    bigO: { time: 'O(V + E)', space: 'O(V + E)' },
    gotchas: [
      'Directed graphs get only u→v — adding both silently breaks toposort',
      'Isolated nodes never appear in the dict — iterate range(n), not graph.keys()',
    ],
    quiz: [
      {
        q: 'For a DIRECTED edge u→v you add…',
        options: ['both directions', 'only graph[u].append(v)', 'only graph[v].append(u)', 'a weight of 1'],
        answer: 1,
        why: 'Direction is information — mirroring it invents edges that do not exist.',
      },
    ],
    problems: [
      { title: 'Number of Connected Components in an Undirected Graph', diff: 'M', slug: 'number-of-connected-components-in-an-undirected-graph' },
      { title: 'Course Schedule', diff: 'M', slug: 'course-schedule' },
      { title: 'Clone Graph', diff: 'M', slug: 'clone-graph' },
    ],
  },
  {
    id: 'graphs/bfs-shortest',
    name: 'BFS shortest path (unweighted)',
    when: 'Fewest steps from A to B when every step costs the same',
    code: [
      'q = deque([(start, 0)])',
      'seen = {start}',
      'while q:',
      '    node, dist = q.popleft()',
      '    if node == goal:',
      '        return dist',
      '    for nxt in graph[node]:',
      '        if nxt {{not in seen}}:',
      '            seen.add({{nxt}})            # mark when ENQUEUED',
      '            q.append((nxt, {{dist + 1}}))',
    ],
    bigO: { time: 'O(V + E)', space: 'O(V)' },
    gotchas: [
      'Mark seen at ENQUEUE time — marking at dequeue lets duplicates flood the queue',
      'BFS finds shortest paths only when edges are UNWEIGHTED (else Dijkstra)',
      'Multi-source BFS: seed the queue with every source at distance 0',
    ],
    quiz: [
      {
        q: 'Marking nodes seen at dequeue (not enqueue) causes…',
        options: [
          'Wrong answers',
          'The same node queued many times — blow-up, though answers stay correct',
          'A crash',
          'Nothing different',
        ],
        answer: 1,
        why: 'Correct but potentially exponential queue growth — the classic BFS perf bug.',
      },
    ],
    problems: [
      { title: 'Rotting Oranges', diff: 'M', slug: 'rotting-oranges' },
      { title: 'Shortest Path in Binary Matrix', diff: 'M', slug: 'shortest-path-in-binary-matrix' },
      { title: 'Open the Lock', diff: 'M', slug: 'open-the-lock' },
      { title: 'Word Ladder', diff: 'H', slug: 'word-ladder' },
    ],
  },
  {
    id: 'graphs/union-find',
    name: 'Union-Find (path compression + rank)',
    when: 'Dynamic connectivity — merge groups and answer "same group?" in near-constant time',
    code: [
      'parent = list(range(n))',
      'rank = [0] * n',
      'def find(x):',
      '    while parent[x] != x:',
      '        parent[x] = {{parent[parent[x]]}}   # path halving',
      '        x = parent[x]',
      '    return x',
      'def union(a, b):',
      '    ra, rb = find(a), find(b)',
      '    if ra == rb:',
      '        return False               # already connected → cycle!',
      '    if rank[ra] < rank[rb]:',
      '        ra, rb = rb, ra',
      '    parent[rb] = {{ra}}',
      '    if rank[ra] == rank[rb]:',
      '        rank[ra] += 1',
      '    return True',
    ],
    bigO: { time: 'O(α(n)) ≈ O(1) amortized per op', space: 'O(n)' },
    gotchas: [
      'union returning False = the edge closes a cycle — free cycle detection',
      'Skip compression and chains degrade find to O(n)',
      'Component count: start at n, subtract 1 per successful union',
    ],
    quiz: [
      {
        q: 'α(n) in the union-find bound is…',
        options: [
          'The golden ratio',
          'Inverse Ackermann — ≤ 5 for any realistic n',
          'log log n',
          'Amortized constant by definition',
        ],
        answer: 1,
        why: 'It grows so slowly it is effectively constant — say this in interviews.',
      },
    ],
    problems: [
      { title: 'Redundant Connection', diff: 'M', slug: 'redundant-connection' },
      { title: 'Number of Connected Components in an Undirected Graph', diff: 'M', slug: 'number-of-connected-components-in-an-undirected-graph' },
      { title: 'Graph Valid Tree', diff: 'M', slug: 'graph-valid-tree' },
      { title: 'Accounts Merge', diff: 'M', slug: 'accounts-merge' },
    ],
  },
  {
    id: 'graphs/topo-sort',
    name: "Topological sort (Kahn's BFS)",
    when: 'Order tasks under prerequisites — and detect when no valid order exists',
    code: [
      'indeg = [0] * n',
      'for u, v in edges:          # u must come before v',
      '    graph[u].append(v)',
      '    indeg[v] += 1',
      'q = deque([i for i in range(n) if {{indeg[i] == 0}}])',
      'order = []',
      'while q:',
      '    u = q.popleft()',
      '    order.append(u)',
      '    for v in graph[u]:',
      '        indeg[v] -= 1',
      '        if {{indeg[v] == 0}}:',
      '            q.append(v)',
      '# len(order) < n  →  cycle',
    ],
    bigO: { time: 'O(V + E)', space: 'O(V + E)' },
    gotchas: [
      'len(order) < n means a cycle — some nodes never reached indegree 0',
      'Seed the queue with ALL zero-indegree nodes, not just one',
      'DFS-with-colors is the recursive alternative for cycle detection',
    ],
    quiz: [
      {
        q: "How does Kahn's algorithm report a cycle?",
        options: [
          'It raises an exception',
          'The output order is shorter than n',
          'indegrees go negative',
          'The queue never empties',
        ],
        answer: 1,
        why: 'Nodes inside a cycle never hit indegree 0, so they never enter the order.',
      },
    ],
    problems: [
      { title: 'Course Schedule', diff: 'M', slug: 'course-schedule' },
      { title: 'Course Schedule II', diff: 'M', slug: 'course-schedule-ii' },
      { title: 'Minimum Height Trees', diff: 'M', slug: 'minimum-height-trees' },
      { title: 'Alien Dictionary', diff: 'H', slug: 'alien-dictionary' },
    ],
  },
  {
    id: 'graphs/dijkstra',
    name: 'Dijkstra with a heap',
    when: 'Shortest paths when edges have different (non-negative) costs',
    code: [
      'dist = {start: 0}',
      'heap = [(0, start)]',
      'while heap:',
      '    d, u = heapq.heappop(heap)',
      '    if d > dist.get(u, {{float("inf")}}):',
      '        continue                  # stale entry — skip',
      '    for v, w in graph[u]:',
      '        nd = {{d + w}}',
      '        if nd < dist.get(v, float("inf")):',
      '            dist[v] = nd',
      '            heapq.heappush(heap, {{(nd, v)}})',
    ],
    bigO: { time: 'O(E log V)', space: 'O(V + E)' },
    gotchas: [
      'Lazy deletion: pop, then SKIP entries worse than the best known distance',
      'Negative edges break the greedy argument — Bellman-Ford instead',
      'The tuple is (distance, node) — priority first, always',
    ],
    quiz: [
      {
        q: 'Dijkstra fails when the graph has…',
        options: ['Cycles', 'Negative-weight edges', 'Disconnected parts', 'More edges than nodes'],
        answer: 1,
        why: 'A negative edge can improve an already-finalized node — the greedy invariant dies.',
      },
    ],
    problems: [
      { title: 'Network Delay Time', diff: 'M', slug: 'network-delay-time' },
      { title: 'Path With Minimum Effort', diff: 'M', slug: 'path-with-minimum-effort' },
      { title: 'Cheapest Flights Within K Stops', diff: 'M', slug: 'cheapest-flights-within-k-stops' },
      { title: 'Swim in Rising Water', diff: 'H', slug: 'swim-in-rising-water' },
    ],
  },
  {
    id: 'graphs/multi-source-bfs',
    name: 'Multi-source BFS',
    when: 'Distance from EVERY cell to its nearest source — seed the queue with all sources at once',
    code: [
      'q = deque()',
      'for r in range(rows):',
      '    for c in range(cols):',
      '        if grid[r][c] == SOURCE:',
      '            q.append({{(r, c, 0)}})     # ALL sources, distance 0',
      '            seen.add((r, c))',
      'while q:',
      '    r, c, d = q.popleft()',
      '    for dr, dc in [(1,0), (-1,0), (0,1), (0,-1)]:',
      '        nr, nc = r + dr, c + dc',
      '        if in_bounds(nr, nc) and (nr, nc) {{not in seen}}:',
      '            seen.add((nr, nc))',
      '            dist[nr][nc] = {{d + 1}}',
      '            q.append((nr, nc, d + 1))',
    ],
    bigO: { time: 'O(rows·cols)', space: 'O(rows·cols)' },
    gotchas: [
      'One BFS from all sources — running BFS per source would be O(cells²)',
      'The wavefront expands one distance-ring per level: nearest source wins automatically',
      'Rotting oranges, walls-and-gates, 01-matrix — all this exact shape',
    ],
    quiz: [
      {
        q: 'Why does seeding every source at distance 0 give NEAREST-source distances?',
        options: [
          'Sources are sorted',
          'BFS explores strictly by distance — whichever wave arrives first is closest',
          'It doesn’t — you need Dijkstra',
          'The grid is small',
        ],
        answer: 1,
        why: 'All waves advance in lock-step; first arrival = minimum distance.',
      },
    ],
    problems: [
      { title: 'Rotting Oranges', diff: 'M', slug: 'rotting-oranges' },
      { title: '01 Matrix', diff: 'M', slug: '01-matrix' },
      { title: 'As Far from Land as Possible', diff: 'M', slug: 'as-far-from-land-as-possible' },
      { title: 'Map of Highest Peak', diff: 'M', slug: 'map-of-highest-peak' },
    ],
  },
  {
    id: 'graphs/clone-map',
    name: 'Deep copy via old→new map',
    when: 'Clone a structure with cycles or cross-links — map each original to its copy first',
    code: [
      'def clone(node, seen={}):',
      '    if not node:',
      '        return None',
      '    if node {{in seen}}:',
      '        return seen[node]           # already cloned — reuse, don’t recurse',
      '    copy = Node(node.val)',
      '    seen[{{node}}] = copy             # register BEFORE recursing!',
      '    for nb in node.neighbors:',
      '        copy.neighbors.append({{clone(nb, seen)}})',
      '    return copy',
    ],
    bigO: { time: 'O(V + E)', space: 'O(V)' },
    gotchas: [
      'Register the copy BEFORE recursing — cycles recurse forever otherwise',
      'The map also handles cross-links: random pointers, shared children',
      'Iterative version: BFS the originals, same seen-map',
    ],
    quiz: [
      {
        q: 'Registering seen[node] after the recursion causes…',
        options: [
          'A memory leak',
          'Infinite recursion on any cycle',
          'Nothing — order is irrelevant',
          'Duplicate edges only',
        ],
        answer: 1,
        why: 'A neighbor that points back finds nothing in the map and recurses into you again.',
      },
    ],
    problems: [
      { title: 'Clone Graph', diff: 'M', slug: 'clone-graph' },
      { title: 'Copy List with Random Pointer', diff: 'M', slug: 'copy-list-with-random-pointer' },
      { title: 'Find Duplicate Subtrees', diff: 'M', slug: 'find-duplicate-subtrees' },
    ],
  },
  {
    id: 'graphs/bipartite',
    name: 'Bipartite check (two-coloring)',
    when: 'Split nodes into two camps with no internal edges — color as you BFS, conflict = impossible',
    code: [
      'color = {}',
      'for s in range(n):                 # graph may be disconnected!',
      '    if s in color:',
      '        continue',
      '    color[s] = 0',
      '    q = deque([s])',
      '    while q:',
      '        u = q.popleft()',
      '        for v in graph[u]:',
      '            if v not in color:',
      '                color[v] = {{color[u] ^ 1}}    # opposite color',
      '                q.append(v)',
      '            elif color[v] {{== color[u]}}:',
      '                return False              # same-color neighbors',
      'return True',
    ],
    bigO: { time: 'O(V + E)', space: 'O(V)' },
    gotchas: [
      'Loop over ALL start nodes — disconnected components hide conflicts',
      'XOR with 1 flips the color; the color dict doubles as the seen set',
      '"Divide into two groups with dislikes/rivalries" = bipartite in disguise',
    ],
    quiz: [
      {
        q: 'A graph is bipartite if and only if it has…',
        options: ['No cycles at all', 'No odd-length cycles', 'No even-length cycles', 'Fewer edges than nodes'],
        answer: 1,
        why: 'An odd cycle forces some adjacent pair to share a color — the classic theorem.',
      },
    ],
    problems: [
      { title: 'Is Graph Bipartite?', diff: 'M', slug: 'is-graph-bipartite' },
      { title: 'Possible Bipartition', diff: 'M', slug: 'possible-bipartition' },
      { title: 'Flower Planting With No Adjacent', diff: 'M', slug: 'flower-planting-with-no-adjacent' },
    ],
  },
  {
    id: 'graphs/mst-prim',
    name: "Minimum spanning tree (Prim's)",
    when: 'Cheapest set of edges connecting EVERYTHING — grow greedily from any node',
    code: [
      'seen = set()',
      'heap = [(0, 0)]                    # (edge cost, node) — start anywhere',
      'total = 0',
      'while len(seen) < n:',
      '    cost, u = heapq.heappop(heap)',
      '    if {{u in seen}}:',
      '        continue                   # lazy deletion',
      '    seen.add(u)',
      '    total += {{cost}}',
      '    for v, w in neighbors(u):',
      '        if v not in seen:',
      '            heapq.heappush(heap, {{(w, v)}})',
    ],
    bigO: { time: 'O(E log E)', space: 'O(E)' },
    gotchas: [
      'Push the raw EDGE weight — Dijkstra pushes d+w; mixing them up is the classic slip',
      "Kruskal is the alternative: sort all edges, union-find, skip cycle-closing edges",
      '"Connect all points/cities at minimum cost" = MST in disguise',
    ],
    quiz: [
      {
        q: "Prim's priority is the edge weight; Dijkstra's is…",
        options: ['Also the edge weight', 'The accumulated path distance d + w', 'The node degree', 'Random'],
        answer: 1,
        why: 'MST minimizes total edge cost; shortest-path minimizes per-node distance — different objectives, one character apart.',
      },
    ],
    problems: [
      { title: 'Min Cost to Connect All Points', diff: 'M', slug: 'min-cost-to-connect-all-points' },
      { title: 'Connecting Cities With Minimum Cost', diff: 'M', slug: 'connecting-cities-with-minimum-cost' },
      { title: 'Find Critical and Pseudo-Critical Edges in MST', diff: 'H', slug: 'find-critical-and-pseudo-critical-edges-in-minimum-spanning-tree' },
    ],
  },
  {
    id: 'graphs/bellman-ford',
    name: 'Bellman-Ford (bounded relaxation)',
    when: 'Shortest path with at most k hops, or with negative edges — relax every edge, k+1 rounds',
    code: [
      'dist = [float("inf")] * n',
      'dist[src] = 0',
      'for _ in range({{k + 1}}):          # paths of at most k+1 edges',
      '    nxt = {{dist[:]}}                # relax against a SNAPSHOT',
      '    for u, v, w in edges:',
      '        if dist[u] + w < nxt[v]:',
      '            nxt[v] = {{dist[u] + w}}',
      '    dist = nxt',
    ],
    bigO: { time: 'O(k · E)', space: 'O(V)' },
    gotchas: [
      'The snapshot stops round i from chaining more than i edges — skip it and k means nothing',
      'Full Bellman-Ford: n−1 rounds; an nth-round improvement proves a negative cycle',
      'This beats Dijkstra exactly when edges are negative or hops are capped',
    ],
    quiz: [
      {
        q: 'Relaxing against dist directly (no snapshot) breaks the k-stops cap because…',
        options: [
          'It is slower',
          'One round can then propagate through many edges — hop counting is lost',
          'Negative edges overflow',
          'It doesn’t break anything',
        ],
        answer: 1,
        why: 'Updates within a round would cascade, letting round 1 build multi-edge paths.',
      },
    ],
    problems: [
      { title: 'Cheapest Flights Within K Stops', diff: 'M', slug: 'cheapest-flights-within-k-stops' },
      { title: 'Network Delay Time', diff: 'M', slug: 'network-delay-time' },
      { title: 'Path With Maximum Probability', diff: 'M', slug: 'path-with-maximum-probability' },
    ],
  },
];
