// World: Recursive ⇄ Iterative — every traversal both ways, and the
// mechanical recipes for converting between them.

export const RECIT_TRICKS = [
  {
    id: 'recit/inorder-iterative',
    name: 'Inorder: left-spine stack',
    when: 'Sorted-order walk of a BST without recursion — run down lefts, pop, hop right',
    code: [
      '# recursive (know it cold): inorder(n.left); visit(n); inorder(n.right)',
      'stack, node = [], root',
      'while {{stack or node}}:',
      '    while node:                   # run down the left spine',
      '        stack.append(node)',
      '        node = {{node.left}}',
      '    node = stack.pop()            # leftmost unvisited',
      '    visit(node)',
      '    node = {{node.right}}          # then its right subtree',
    ],
    bigO: { time: 'O(n)', space: 'O(h)' },
    gotchas: [
      'Loop on `stack OR node` — either alone quits early',
      'This is THE template for kth-smallest-in-BST: stop at the kth pop',
      'BST iterator: keep the stack as instance state, next() = one pop-and-hop',
    ],
    quiz: [
      {
        q: 'Inorder traversal of a BST visits values in…',
        options: ['Insertion order', 'Sorted ascending order', 'Level order', 'Random order'],
        answer: 1,
        why: 'Left < node < right, applied recursively — the defining BST property.',
      },
    ],
    problems: [
      { title: 'Binary Tree Inorder Traversal', diff: 'E', slug: 'binary-tree-inorder-traversal' },
      { title: 'Kth Smallest Element in a BST', diff: 'M', slug: 'kth-smallest-element-in-a-bst' },
      { title: 'Binary Search Tree Iterator', diff: 'M', slug: 'binary-search-tree-iterator' },
      { title: 'Validate Binary Search Tree', diff: 'M', slug: 'validate-binary-search-tree' },
    ],
  },
  {
    id: 'recit/postorder-iterative',
    name: 'Postorder: reversed modified preorder',
    when: 'Children before parent, no recursion — walk root-right-left, then flip it',
    code: [
      '# recursive: post(n.left); post(n.right); visit(n)',
      'stack, out = [root], []',
      'while stack:',
      '    node = stack.pop()',
      '    out.append(node.val)          # root FIRST (like preorder)',
      '    if node.left:',
      '        stack.append({{node.left}})   # left pushed first…',
      '    if node.right:',
      '        stack.append(node.right)     # …so right pops first',
      'return out{{[::-1]}}                  # root-right-left reversed = postorder',
    ],
    bigO: { time: 'O(n)', space: 'O(n)' },
    gotchas: [
      'root-right-left reversed IS left-right-root — say the identity out loud',
      'Compare iterative preorder: push right-then-left, and do NOT reverse',
      'True streaming one-stack postorder needs visited flags — see the frames recipe',
    ],
    quiz: [
      {
        q: 'Reversing a root→right→left walk yields…',
        options: ['Preorder', 'Inorder', 'Postorder', 'Level order'],
        answer: 2,
        why: 'Reverse(root, right, left) = (left, right, root) — children before parent.',
      },
    ],
    problems: [
      { title: 'Binary Tree Postorder Traversal', diff: 'E', slug: 'binary-tree-postorder-traversal' },
      { title: 'N-ary Tree Postorder Traversal', diff: 'E', slug: 'n-ary-tree-postorder-traversal' },
      { title: 'Flatten Binary Tree to Linked List', diff: 'M', slug: 'flatten-binary-tree-to-linked-list' },
    ],
  },
  {
    id: 'recit/frames',
    name: 'The frames recipe: (node, expanded)',
    when: 'Mechanically convert ANY recursion to a loop — frames remember where you were',
    code: [
      'stack = [(root, {{False}})]         # (node, expanded?)',
      'while stack:',
      '    node, expanded = stack.pop()',
      '    if not node:',
      '        continue',
      '    if expanded:',
      '        visit(node)                # the "after children" position',
      '    else:',
      '        # push in REVERSE of desired execution order:',
      '        stack.append({{(node, True)}})     # revisit after children → postorder',
      '        stack.append((node.right, False))',
      '        stack.append({{(node.left, False)}})',
    ],
    bigO: { time: 'O(n)', space: 'O(h)' },
    gotchas: [
      'Where (node, True) sits among the pushes selects pre/in/post-order',
      'Pushes happen in REVERSE of execution order — the stack flips them back',
      'One recipe replaces three memorized templates — this is the master key',
    ],
    quiz: [
      {
        q: 'Pushing right, then (node, True), then left produces which order?',
        options: ['Preorder', 'Inorder', 'Postorder', 'Reverse level order'],
        answer: 1,
        why: 'Pops run left → node → right — the inorder execution sequence.',
      },
    ],
    problems: [
      { title: 'Binary Tree Inorder Traversal', diff: 'E', slug: 'binary-tree-inorder-traversal' },
      { title: 'Binary Tree Postorder Traversal', diff: 'E', slug: 'binary-tree-postorder-traversal' },
      { title: 'N-ary Tree Preorder Traversal', diff: 'E', slug: 'n-ary-tree-preorder-traversal' },
    ],
  },
  {
    id: 'recit/graph-dfs-both',
    name: 'Graph DFS: recursion vs explicit stack',
    when: 'Deep graphs blow Python’s ~1000-frame recursion limit — carry both versions',
    code: [
      'def dfs(u):                        # recursive',
      '    seen.add(u)',
      '    for v in graph[u]:',
      '        if v not in seen:',
      '            {{dfs(v)}}',
      '',
      'stack = [start]                    # iterative — no depth limit',
      'seen = {start}',
      'while stack:',
      '    u = stack.pop()',
      '    for v in graph[u]:',
      '        if v {{not in seen}}:',
      '            seen.add(v)            # mark at PUSH time',
      '            stack.append({{v}})',
    ],
    bigO: { time: 'O(V + E)', space: 'O(V)' },
    gotchas: [
      'A 10⁵-node path graph CRASHES recursive DFS (RecursionError ~1000 frames)',
      'The iterative version visits neighbors in reverse order — same set, different order',
      'sys.setrecursionlimit is a band-aid; the stack version is the cure',
    ],
    quiz: [
      {
        q: 'Recursive DFS on a 100,000-node chain graph in Python…',
        options: [
          'Works fine',
          'Raises RecursionError — the default limit is ~1000 frames',
          'Is faster than iterative',
          'Silently skips nodes',
        ],
        answer: 1,
        why: 'Every edge deepens the call stack by one — chains are the killer case.',
      },
    ],
    problems: [
      { title: 'Number of Islands', diff: 'M', slug: 'number-of-islands' },
      { title: 'Clone Graph', diff: 'M', slug: 'clone-graph' },
      { title: 'Keys and Rooms', diff: 'M', slug: 'keys-and-rooms' },
      { title: 'Max Area of Island', diff: 'M', slug: 'max-area-of-island' },
    ],
  },
  {
    id: 'recit/stack-vs-queue',
    name: 'Stack ⇄ queue flips DFS ⇄ BFS',
    when: 'One traversal skeleton, two orders — popping deep vs popping wide',
    code: [
      'frontier = deque([start])',
      'seen = {start}',
      'while frontier:',
      '    node = frontier{{.pop()}}        # LIFO → DFS (deep first)',
      '    # node = frontier{{.popleft()}}  # FIFO → BFS (wide first)',
      '    for nxt in neighbors(node):',
      '        if nxt not in seen:',
      '            seen.add(nxt)',
      '            frontier.append({{nxt}})',
    ],
    bigO: { time: 'O(V + E)', space: 'O(V)' },
    gotchas: [
      'ONE method call of difference — everything else is identical',
      'Shortest path in an unweighted graph REQUIRES popleft (BFS)',
      'Mere reachability / connectivity: either order works — pick the cheaper mental model',
    ],
    quiz: [
      {
        q: 'Which pop gives shortest paths in an unweighted graph?',
        options: ['pop() — DFS', 'popleft() — BFS', 'Either', 'Neither — you need Dijkstra'],
        answer: 1,
        why: 'BFS explores strictly by distance rings; DFS wanders arbitrarily deep first.',
      },
    ],
    problems: [
      { title: 'Number of Islands', diff: 'M', slug: 'number-of-islands' },
      { title: 'Rotting Oranges', diff: 'M', slug: 'rotting-oranges' },
      { title: 'Keys and Rooms', diff: 'M', slug: 'keys-and-rooms' },
      { title: 'Word Ladder', diff: 'H', slug: 'word-ladder' },
    ],
  },
];
