// World: Tries (prefix trees)

export const TRIES_TRICKS = [
  {
    id: 'tries/node-class',
    name: 'TrieNode insert/search template',
    when: 'Store many words for fast prefix-based lookup — the canonical class',
    code: [
      'class TrieNode:',
      '    def __init__(self):',
      '        self.children = {}',
      '        self.end = {{False}}',
      '',
      'def insert(root, word):',
      '    node = root',
      '    for ch in word:',
      '        if ch not in node.children:',
      '            node.children[ch] = {{TrieNode()}}',
      '        node = node.children[ch]',
      '    node.end = True',
    ],
    bigO: { time: 'O(L) per insert/search (L = word length)', space: 'O(total characters)' },
    gotchas: [
      'The end flag is what separates a real word from a mere prefix',
      'Walk with node = node.children[ch] — forgetting to advance is the classic bug',
    ],
    quiz: [
      {
        q: 'Searching a word of length L in a trie with n words costs…',
        options: ['O(L)', 'O(log n)', 'O(n)', 'O(n·L)'],
        answer: 0,
        why: 'One child-hop per character — independent of how many words are stored.',
      },
    ],
    problems: [
      { title: 'Implement Trie (Prefix Tree)', diff: 'M', slug: 'implement-trie-prefix-tree' },
      { title: 'Design Add and Search Words Data Structure', diff: 'M', slug: 'design-add-and-search-words-data-structure' },
      { title: 'Word Search II', diff: 'H', slug: 'word-search-ii' },
    ],
  },
  {
    id: 'tries/dict-trie',
    name: 'Nested-dict quick trie',
    when: 'You want trie behavior in five lines, no class ceremony',
    code: [
      'trie = {}',
      'for word in words:',
      '    node = trie',
      '    for ch in word:',
      '        node = node.{{setdefault}}(ch, {})',
      '    node[{{"$"}}] = word          # end marker holds the word',
    ],
    bigO: { time: 'O(L) per word', space: 'O(total characters)' },
    gotchas: [
      'setdefault gets-or-creates the child in one call',
      'Use a sentinel key ("$") that can never be a character',
      'Storing the full word at the marker saves rebuilding it during DFS',
    ],
    quiz: [
      {
        q: 'node.setdefault(ch, {}) does what when ch exists?',
        options: [
          'Overwrites it with {}',
          'Returns the existing child unchanged',
          'Raises KeyError',
          'Deletes it',
        ],
        answer: 1,
        why: 'setdefault only inserts when missing — otherwise it is just a lookup.',
      },
    ],
    problems: [
      { title: 'Word Search II', diff: 'H', slug: 'word-search-ii' },
      { title: 'Replace Words', diff: 'M', slug: 'replace-words' },
      { title: 'Longest Word in Dictionary', diff: 'M', slug: 'longest-word-in-dictionary' },
    ],
  },
  {
    id: 'tries/prefix-search',
    name: 'Word vs prefix search',
    when: 'Distinguish "is this a stored word?" from "does anything start with this?"',
    code: [
      'def walk(root, s):',
      '    node = root',
      '    for ch in s:',
      '        if ch not in node.children:',
      '            return {{None}}',
      '        node = node.children[ch]',
      '    return node',
      '',
      'def search(root, word):',
      '    node = walk(root, word)',
      '    return node is not None and {{node.end}}',
      '',
      'def starts_with(root, prefix):',
      '    return walk(root, prefix) {{is not None}}',
    ],
    bigO: { time: 'O(L)', space: 'O(1) extra' },
    gotchas: [
      'Same walk, different final check — factor it out',
      'search must check node.end; startsWith must NOT',
    ],
    quiz: [
      {
        q: 'After inserting only "apple", search("app") returns…',
        options: ['True', 'False', 'KeyError', 'None'],
        answer: 1,
        why: 'The path exists but no end-flag sits at "app" — it is a prefix, not a word.',
      },
    ],
    problems: [
      { title: 'Implement Trie (Prefix Tree)', diff: 'M', slug: 'implement-trie-prefix-tree' },
      { title: 'Search Suggestions System', diff: 'M', slug: 'search-suggestions-system' },
      { title: 'Longest Common Prefix', diff: 'E', slug: 'longest-common-prefix' },
    ],
  },
  {
    id: 'tries/wildcard-dfs',
    name: 'Wildcard search (DFS over the trie)',
    when: 'Search with "." matching any character — branch into every child',
    code: [
      'def search(node, word, i=0):',
      '    if i == len(word):',
      '        return {{node.end}}',
      '    ch = word[i]',
      '    if ch == ".":',
      '        return {{any}}(search(child, word, i + 1)',
      '                   for child in node.children.values())',
      '    if ch not in node.children:',
      '        return False',
      '    return search({{node.children[ch]}}, word, i + 1)',
    ],
    bigO: { time: 'O(26^dots · L) worst case', space: 'O(L) recursion' },
    gotchas: [
      'A "." fans out to ALL children — any() short-circuits on the first hit',
      'Regular characters stay O(1) — only wildcards branch',
    ],
    quiz: [
      {
        q: 'Why any() over the children for "."?',
        options: [
          'To visit them in sorted order',
          'One matching branch is enough — and any() stops there',
          'all() would also work',
          'To avoid recursion',
        ],
        answer: 1,
        why: 'Existential search: succeed if at least one child path matches.',
      },
    ],
    problems: [
      { title: 'Design Add and Search Words Data Structure', diff: 'M', slug: 'design-add-and-search-words-data-structure' },
      { title: 'Word Search II', diff: 'H', slug: 'word-search-ii' },
      { title: 'Prefix and Suffix Search', diff: 'H', slug: 'prefix-and-suffix-search' },
    ],
  },
  {
    id: 'tries/board-prune',
    name: 'Trie + board backtracking',
    when: 'Find MANY words in one grid — walk board and trie together, prune dead prefixes',
    code: [
      'def dfs(r, c, node):',
      '    ch = board[r][c]',
      '    if ch {{not in node.children}}:',
      '        return                        # prune: no word continues here',
      '    node = node.children[ch]',
      '    if node.end:',
      '        found.add(node.word)',
      '    board[r][c] = {{"#"}}              # mark visited',
      '    for dr, dc in [(1,0), (-1,0), (0,1), (0,-1)]:',
      '        if 0 <= r+dr < rows and 0 <= c+dc < cols:',
      '            dfs(r + dr, c + dc, node)',
      '    board[r][c] = {{ch}}               # restore on the way out',
    ],
    bigO: { time: 'O(cells · 4^maxLen) with heavy pruning', space: 'O(trie + path)' },
    gotchas: [
      'Searching each word separately re-walks the board per word — the trie shares prefixes',
      'Restore the cell after recursion (backtracking!), not before',
      'Prune harder: delete trie leaves once their word is found',
    ],
    quiz: [
      {
        q: 'Why a trie instead of checking each word with its own DFS?',
        options: [
          'Tries use less code',
          'Shared prefixes are explored once for ALL words',
          'DFS cannot find multiple words',
          'It avoids recursion',
        ],
        answer: 1,
        why: '"cat" and "car" share the "ca" walk — per-word search repeats it.',
      },
    ],
    problems: [
      { title: 'Word Search II', diff: 'H', slug: 'word-search-ii' },
      { title: 'Word Search', diff: 'M', slug: 'word-search' },
      { title: 'Search Suggestions System', diff: 'M', slug: 'search-suggestions-system' },
    ],
  },
];
