// World: Design & Structures

export const DESIGN_TRICKS = [
  {
    id: 'design/lru',
    name: 'LRU cache via OrderedDict',
    when: 'Evict the least-recently-used entry at capacity — recency IS insertion order',
    code: [
      'from collections import OrderedDict',
      'cache = OrderedDict()',
      'def get(key):',
      '    if key not in cache:',
      '        return -1',
      '    cache.{{move_to_end}}(key)          # touched → most recent',
      '    return cache[key]',
      'def put(key, val):',
      '    if key in cache:',
      '        cache.move_to_end(key)',
      '    cache[key] = val',
      '    if len(cache) > cap:',
      '        cache.popitem(last={{False}})    # evict the OLDEST',
    ],
    bigO: { time: 'O(1) get/put', space: 'O(capacity)' },
    gotchas: [
      'popitem(last=False) pops the least-recent end; last=True would evict the newest',
      'The from-scratch version is a hashmap + doubly-linked list — know both stories',
      'Plain dicts keep insertion order too, but lack move_to_end/popitem(False)',
    ],
    quiz: [
      {
        q: 'Building LRU without OrderedDict needs a hashmap plus…',
        options: ['A heap', 'A doubly-linked list', 'A balanced BST', 'Two stacks'],
        answer: 1,
        why: 'O(1) removal from the middle + O(1) move-to-front — only a DLL gives both.',
      },
    ],
    problems: [
      { title: 'LRU Cache', diff: 'M', slug: 'lru-cache' },
      { title: 'LFU Cache', diff: 'H', slug: 'lfu-cache' },
      { title: 'Design Browser History', diff: 'M', slug: 'design-browser-history' },
    ],
  },
  {
    id: 'design/swap-pop',
    name: 'O(1) delete: swap with last, pop',
    when: 'A set with O(1) insert, delete AND getRandom — dict of positions over a list',
    code: [
      'vals, pos = [], {}              # list + value→index map',
      'def insert(x):',
      '    pos[x] = len(vals)',
      '    vals.append(x)',
      'def remove(x):',
      '    i, last = pos[x], vals[-1]',
      '    vals[i], pos[last] = {{last}}, {{i}}   # move last into the hole',
      '    vals.pop()',
      '    del pos[x]',
      'def get_random():',
      '    return vals[{{random.randrange(len(vals))}}]',
    ],
    bigO: { time: 'O(1) all ops', space: 'O(n)' },
    gotchas: [
      'list.remove(x) is O(n) — the swap-with-last dance is the whole trick',
      'Update the moved element’s index in pos BEFORE popping',
      'getRandom needs a LIST — sets/dicts cannot be indexed uniformly',
    ],
    quiz: [
      {
        q: 'Why can’t a plain set back getRandom?',
        options: [
          'Sets are unordered so random is impossible',
          'Uniform random needs O(1) indexing — sets don’t support s[i]',
          'Sets are slower',
          'random.choice rejects sets… and that is the only reason',
        ],
        answer: 1,
        why: 'random.choice needs a sequence; converting the set each call is O(n).',
      },
    ],
    problems: [
      { title: 'Insert Delete GetRandom O(1)', diff: 'M', slug: 'insert-delete-getrandom-o1' },
      { title: 'Insert Delete GetRandom O(1) - Duplicates allowed', diff: 'H', slug: 'insert-delete-getrandom-o1-duplicates-allowed' },
      { title: 'Design Underground System', diff: 'M', slug: 'design-underground-system' },
    ],
  },
  {
    id: 'design/serialize',
    name: 'Tree serialization (preorder + null markers)',
    when: 'Turn a tree into a string and back — nulls make the shape unambiguous',
    code: [
      'def serialize(node):',
      '    if not node:',
      '        return {{"N"}}                  # null marker',
      '    return f"{node.val},{serialize(node.left)},{serialize(node.right)}"',
      '',
      'def deserialize(data):',
      '    vals = iter(data.split(","))',
      '    def build():',
      '        v = {{next(vals)}}',
      '        if v == "N":',
      '            return None',
      '        node = TreeNode(int(v))',
      '        node.left = {{build()}}',
      '        node.right = build()',
      '        return node',
      '    return build()',
    ],
    bigO: { time: 'O(n)', space: 'O(n)' },
    gotchas: [
      'Preorder + explicit nulls uniquely determines the tree — no second traversal needed',
      'iter() + next() consumes tokens in exactly the order build() wants them',
      'The same idea fingerprints subtrees for duplicate detection',
    ],
    quiz: [
      {
        q: 'Why are the null markers required?',
        options: [
          'They compress the output',
          'Without them, preorder alone can describe many different shapes',
          'JSON needs them',
          'They speed up parsing',
        ],
        answer: 1,
        why: '"1,2" could be left child or right child — "1,2,N,N,N" cannot.',
      },
    ],
    problems: [
      { title: 'Serialize and Deserialize Binary Tree', diff: 'H', slug: 'serialize-and-deserialize-binary-tree' },
      { title: 'Find Duplicate Subtrees', diff: 'M', slug: 'find-duplicate-subtrees' },
      { title: 'Subtree of Another Tree', diff: 'E', slug: 'subtree-of-another-tree' },
    ],
  },
  {
    id: 'design/length-prefix',
    name: 'Length-prefix string encoding',
    when: 'Join many strings into one, reversibly — even when they contain your delimiter',
    code: [
      'def encode(strs):',
      '    return "".join(str(len(s)) + "#" + s for s in strs)',
      '',
      'def decode(data):',
      '    out, i = [], 0',
      '    while i < len(data):',
      '        j = data.index({{"#"}}, i)',
      '        length = int(data[i:j])',
      '        out.append(data[j + 1 : {{j + 1 + length}}])',
      '        i = j + 1 + length',
      '    return out',
    ],
    bigO: { time: 'O(total length)', space: 'O(total length)' },
    gotchas: [
      'Any delimiter alone fails — the payload may contain it; the LENGTH disambiguates',
      'This is how real wire protocols frame messages (netstrings)',
    ],
    quiz: [
      {
        q: 'Why not just join with an unlikely separator like "🦄"?',
        options: [
          'Emoji are slow',
          'Inputs are arbitrary — any separator can appear in a payload',
          'It works fine',
          'join() rejects emoji',
        ],
        answer: 1,
        why: 'Correctness must not depend on "unlikely" — the length prefix is airtight.',
      },
    ],
    problems: [
      { title: 'Encode and Decode Strings', diff: 'M', slug: 'encode-and-decode-strings' },
      { title: 'Serialize and Deserialize Binary Tree', diff: 'H', slug: 'serialize-and-deserialize-binary-tree' },
      { title: 'Design Compressed String Iterator', diff: 'E', slug: 'design-compressed-string-iterator' },
    ],
  },
  {
    id: 'design/window-deque',
    name: 'Time-window counter (deque)',
    when: 'Count events in the last N time units — expire old entries from the front',
    code: [
      'from collections import deque',
      'events = deque()',
      'def ping(t):',
      '    events.append({{t}})',
      '    while events[0] < {{t - 3000}}:     # expire outside the window',
      '        events{{.popleft()}}',
      '    return len(events)',
    ],
    bigO: { time: 'amortized O(1) per ping', space: 'O(window size)' },
    gotchas: [
      'Each event enters and leaves the deque once — that is the amortized argument',
      'Same skeleton: moving averages, rate limiters, sliding-window logs',
    ],
    quiz: [
      {
        q: 'Total work over n pings is O(n) because…',
        options: [
          'The while loop rarely runs',
          'Every event is appended once and popped at most once',
          'deque is magic',
          'It is actually O(n²)',
        ],
        answer: 1,
        why: 'Charge each pop to its original append — classic amortization.',
      },
    ],
    problems: [
      { title: 'Number of Recent Calls', diff: 'E', slug: 'number-of-recent-calls' },
      { title: 'Moving Average from Data Stream', diff: 'E', slug: 'moving-average-from-data-stream' },
      { title: 'Design Hit Counter', diff: 'M', slug: 'design-hit-counter' },
    ],
  },
];
