// World: Sorting & Selection

export const SORTING_TRICKS = [
  {
    id: 'sorting/quickselect',
    name: 'Quickselect (partition, don’t sort)',
    when: 'The kth largest/smallest element — average O(n), no full sort',
    code: [
      'def quickselect(lo, hi, k):        # k = target index if sorted',
      '    pivot = nums[hi]',
      '    p = lo',
      '    for i in range(lo, hi):',
      '        if nums[i] <= pivot:',
      '            nums[i], nums[p] = nums[p], nums[i]',
      '            {{p += 1}}',
      '    nums[p], nums[hi] = nums[hi], nums[p]',
      '    if p == k:',
      '        return nums[p]',
      '    if p < k:',
      '        return quickselect({{p + 1}}, hi, k)',
      '    return quickselect(lo, {{p - 1}}, k)',
    ],
    bigO: { time: 'O(n) average, O(n²) worst', space: 'O(1) (tail recursion)' },
    gotchas: [
      'Recurse into ONE side only — that is why it beats quicksort’s O(n log n)',
      'kth LARGEST = index len(nums)-k if sorted ascending',
      'Adversarial worst case is O(n²) — mention random pivots in interviews',
    ],
    quiz: [
      {
        q: 'Average time of quickselect vs full sort for one order statistic?',
        options: ['O(n) vs O(n log n)', 'O(log n) vs O(n)', 'Same', 'O(n²) vs O(n log n)'],
        answer: 0,
        why: 'n + n/2 + n/4 + … = 2n — halving work, one side only.',
      },
    ],
    problems: [
      { title: 'Kth Largest Element in an Array', diff: 'M', slug: 'kth-largest-element-in-an-array' },
      { title: 'K Closest Points to Origin', diff: 'M', slug: 'k-closest-points-to-origin' },
      { title: 'Top K Frequent Elements', diff: 'M', slug: 'top-k-frequent-elements' },
    ],
  },
  {
    id: 'sorting/bucket',
    name: 'Bucket sort by frequency',
    when: 'Values bounded by n (like counts ≤ array length) — index-as-value beats comparison sorting',
    code: [
      'freq = Counter(nums)',
      'buckets = [[] for _ in range({{len(nums) + 1}})]',
      'for val, count in freq.items():',
      '    buckets[{{count}}].append(val)     # index = frequency',
      'res = []',
      'for count in range(len(buckets) - 1, 0, {{-1}}):   # high to low',
      '    for val in buckets[count]:',
      '        res.append(val)',
      '        if len(res) == k:',
      '            return res',
    ],
    bigO: { time: 'O(n)', space: 'O(n)' },
    gotchas: [
      'Works because a frequency can never exceed n — the bucket range is bounded',
      'This is the O(n) answer to top-k-frequent when they veto the heap',
    ],
    quiz: [
      {
        q: 'Bucket sort beats O(n log n) here because…',
        options: [
          'It compares faster',
          'Frequencies are integers bounded by n — indexable, no comparisons needed',
          'Python lists are magic',
          'It doesn’t — it is also O(n log n)',
        ],
        answer: 1,
        why: 'Comparison sorts are Ω(n log n); bounded integer keys escape that bound.',
      },
    ],
    problems: [
      { title: 'Top K Frequent Elements', diff: 'M', slug: 'top-k-frequent-elements' },
      { title: 'Sort Characters By Frequency', diff: 'M', slug: 'sort-characters-by-frequency' },
      { title: 'Maximum Gap', diff: 'M', slug: 'maximum-gap' },
    ],
  },
  {
    id: 'sorting/counting',
    name: 'Counting sort',
    when: 'Tiny value range (colors 0-2, letters, ages) — count then rewrite',
    code: [
      'counts = [0] * 3                  # known value range',
      'for x in nums:',
      '    counts[{{x}}] += 1',
      'i = 0',
      'for val in range(3):',
      '    for _ in range({{counts[val]}}):',
      '        nums[i] = {{val}}',
      '        i += 1',
    ],
    bigO: { time: 'O(n + range)', space: 'O(range)' },
    gotchas: [
      'Two passes, zero comparisons — only valid when the range is small and known',
      'Sort Colors: this two-pass version, or one-pass Dutch flag (pointers world)',
    ],
    quiz: [
      {
        q: 'Counting sort on values 0..10⁹ is a bad idea because…',
        options: [
          'Too many comparisons',
          'The counts array is as big as the value RANGE',
          'It is unstable',
          'Python forbids it',
        ],
        answer: 1,
        why: 'O(n + range) — a billion-slot array for ten numbers.',
      },
    ],
    problems: [
      { title: 'Sort Colors', diff: 'M', slug: 'sort-colors' },
      { title: 'Relative Sort Array', diff: 'E', slug: 'relative-sort-array' },
      { title: 'Height Checker', diff: 'E', slug: 'height-checker' },
    ],
  },
  {
    id: 'sorting/merge-from-back',
    name: 'Merge sorted arrays from the BACK',
    when: 'Merge into an array with trailing free space — fill from the end, never shift',
    code: [
      'i, j = m - 1, n - 1               # ends of the real data',
      'for w in range({{m + n - 1}}, -1, -1):   # write pointer, from the back',
      '    if j < 0 or (i >= 0 and nums1[i] {{> nums2[j]}}):',
      '        nums1[w] = nums1[i]',
      '        i -= 1',
      '    else:',
      '        nums1[w] = nums2[j]',
      '        {{j -= 1}}',
    ],
    bigO: { time: 'O(m + n)', space: 'O(1)' },
    gotchas: [
      'Writing forward would overwrite unread nums1 values — backward never collides',
      'The j < 0 guard lets leftover nums1 elements stay put for free',
    ],
    quiz: [
      {
        q: 'Why start writing at the END of nums1?',
        options: [
          'It is faster in CPython',
          'The write position never catches the unread data — no overwrites',
          'Sorted order requires it',
          'To avoid negative indices',
        ],
        answer: 1,
        why: 'The free space is at the back; consuming it backward keeps reads safe.',
      },
    ],
    problems: [
      { title: 'Merge Sorted Array', diff: 'E', slug: 'merge-sorted-array' },
      { title: 'Squares of a Sorted Array', diff: 'E', slug: 'squares-of-a-sorted-array' },
      { title: 'Interval List Intersections', diff: 'M', slug: 'interval-list-intersections' },
    ],
  },
  {
    id: 'sorting/merge-sort-list',
    name: 'Merge sort on a linked list',
    when: 'Sort a linked list in O(n log n) with O(1) extra — arrays can’t do this in place',
    code: [
      'def sort_list(head):',
      '    if not head or not head.next:',
      '        return head',
      '    slow, fast = head, head.next      # fast starts AHEAD',
      '    while fast and fast.next:',
      '        slow, fast = slow.next, fast.next.next',
      '    mid = {{slow.next}}',
      '    slow.next = {{None}}               # cut the list in two',
      '    left = sort_list(head)',
      '    right = sort_list(mid)',
      '    return {{merge(left, right)}}       # sorted-merge template',
    ],
    bigO: { time: 'O(n log n)', space: 'O(log n) recursion' },
    gotchas: [
      'fast starts at head.next so slow lands BEFORE the middle — clean split for 2 nodes',
      'Cut with slow.next = None or the halves stay connected and recursion never ends',
      'Reuses the merge-two-sorted-lists template as the combine step',
    ],
    quiz: [
      {
        q: 'Why merge sort (not quicksort) for linked lists?',
        options: [
          'Quicksort is always worse',
          'Sequential access suits merging; random-access pivot partitioning suits arrays',
          'Linked lists cannot be split',
          'Interviewers prefer it',
        ],
        answer: 1,
        why: 'Lists lack O(1) indexing — but splitting and splicing them is free.',
      },
    ],
    problems: [
      { title: 'Sort List', diff: 'M', slug: 'sort-list' },
      { title: 'Merge Two Sorted Lists', diff: 'E', slug: 'merge-two-sorted-lists' },
      { title: 'Merge K Sorted Lists', diff: 'H', slug: 'merge-k-sorted-lists' },
    ],
  },
];
